### ISSUE TITLE
Dúvidas sobre contribuição.

### ISSUE THREAD

**Issue by Icegreeen** [iuricode/desafios-frontend#1]
Sobre o Mockup das aplicações no figma, quem é que desenvolve, a pessoa que está contribuindo ou o mantenedor do repositório ?

Tenho algumas ideias de desafios disponíveis no youtube e no github, mas a coluna do link do Figma e de uma Demo são responsabilidades que fogem um pouco do trabalho de um contribuidor.

Ah, outra sugestão, no CONTRIBUTING.md deixe um passo a passo ou algumas regras ou dúvidas para ser mais acessível a quem quer contribuir ao repositório.

**Comment by iuricode** [comment]
Olá!

Eu sou o criador dos designs no Figma.

Este repositório são apenas para desafios da comunidade Codelândia, no momento não estamos aceitando ideias de outros desafios.

Agradeço a sugestão, irei adicionar um passo a passo nele.

Abraço
